// eslint-disable-next-line no-unused-vars
import { eventcontext } from './event.context';

function Eventprovider({ children }) {
  const eventext = [
    {
      title: 'IPL Auction',
      id: '6',
      image:
        'https://firebasestorage.googleapis.com/v0/b/tekhora-26.firebasestorage.app/o/ipl_auction.webp?alt=media&token=35d881d0-8af5-410f-8904-e3907d53d5bb',
      backside: './assets/Hopper.webp',
      description: `IPL Auction is a team-based strategic quiz and auction event inspired by the Indian Premier League auctions.
Participants must answer quiz questions to qualify for the next round and then use the given budget wisely in a live player auction.
Success depends on cricket knowledge, smart bidding, team balance, and strategy under pressure.`,
      category: 'Non-Technical',
      teamSize: '2-3',
      date: 'Feb 21',
      time: '9:30 AM',
      rules: [
        'Each team must consist of 2 participants',
        'Use of mobile phones or internet is strictly prohibited',
        'Any malpractice leads to immediate disqualification',
        'Judges and coordinators’ decisions are final',
        'Teams must report 5 minutes before the scheduled time',
        'Rules may be modified by organizers if required',
      ],
      fees: 50,
      wplink: 'https://chat.whatsapp.com/Bgu30rlpEWN3QKdRYLbfkS',
      contact: {
        name1: 'Abinash',
        phone1: '6383467363',
        name2: 'Joel',
        phone2: '6381165383',
      },
      fallbackImage: './assets/fall_back/ipl_auction.webp',
    },
    {
      title: 'Call Of Query',
      id: '3',
      image:
        'https://firebasestorage.googleapis.com/v0/b/tekhora-26.firebasestorage.app/o/Call%20of%20Query.webp?alt=media&token=ac11a7fd-7fa9-4baf-8a35-50cc75ef90dc',
      backside: './assets/Eleven.webp',
      description: `Think fast, query smart! This event tests your proficiency in DBMS concepts including SQL, transaction management,
and relational logic through multiple challenging rounds.`,
      teamSize: '2-3',
      category: 'Technical',
      date: 'Feb 21',
      time: '9:30 AM',
      rules: [
        'Only registered teams are allowed',
        'Up to 2 members per team in the first round',
        'Final round is individual participation',
        'Prelims consist of objective questions',
        'Finals include advanced and descriptive questions',
      ],
      fees: 60,
      wplink: 'https://chat.whatsapp.com/LUTLQOXFkms1dkmOXNrfVA',
      contact: {
        name1: 'Surya',
        phone1: '8148124727',
        name2: 'Jayasree',
        phone2: '8072064228',
      },
      fallbackImage: './assets/fall_back/call_of_query.webp',
    },
    {
      title: 'Connextions',
      id: '8',
      image:
        'https://firebasestorage.googleapis.com/v0/b/tekhora-26.firebasestorage.app/o/connexions.webp?alt=media&token=6511287b-6f91-4931-acb5-d3aaaf928afe',
      backside: './assets/steve.webp',
      teamSize: '2-3',
      description: `Participants are given sets of images and must identify a hidden connection or common theme linking them together.`,
      category: 'Non-Technical',
      date: 'Feb 21',
      time: '9:30 AM',
      rules: [
        'Only registered teams are allowed',
        'The competition has Prelims and Finals',
        'Each round contains image-based questions',
        'Answers must be submitted within the time limit',
        'Finals consist of 5 segments including tie-breaker',
        'Host decision is final',
      ],
      fees: 50,
      wplink: 'https://chat.whatsapp.com/KW7meAXZd0lFkk28eMumZq',
      contact: {
        name1: 'Itikash',
        phone1: '9786398639',
        name2: 'Karthikeyan',
        phone2: '8825535520',
      },
      fallbackImage: './assets/fall_back/connextions.webp',
    },
    {
      title: 'Tournament of strategies',
      id: '1',
      image:
        'https://firebasestorage.googleapis.com/v0/b/tekhora-26.firebasestorage.app/o/TOS%20(1).webp?alt=media&token=db6719c5-0e5f-40fa-96f2-829aa2754938',
      backside: './assets/Mike.webp',
      description: `A mind sport where strategy matters more than coding. Participants submit a game plan which competes in an
organizer-designed game testing logic, creativity, and adaptability.`,
      category: 'Technical',
      date: 'Feb 21',
      teamSize: '2-3',
      time: '9:30 AM',
      rules: [
        'Participants do not code',
        'Organizers execute the strategies',
        'No fixed rules – creativity is encouraged',
        'Internet usage is allowed',
        'Strategies may exploit loopholes',
        'Outcome depends entirely on strategic thinking',
      ],
      fees: 60,
      wplink: 'https://chat.whatsapp.com/HjNWy91PROw7FLJKsL3zWT',
      contact: {
        name1: 'Chandru',
        phone1: '7667634519',
        name2: 'Mirsha',
        phone2: '9940358967',
      },
      fallbackImage: './assets/fall_back/tos.webp',
    },
    {
      title: 'Treasure Hunt',
      id: '9',
      image:
        'https://firebasestorage.googleapis.com/v0/b/tekhora-26.firebasestorage.app/o/treasure_hunt.webp?alt=media&token=f96788da-66df-4d17-b387-16ad8aaf3225',
      backside: './assets/will.webp',
      teamSize: '2-3',
      description: `A thrilling clue-based hunt across the college campus involving puzzles, twists, and QR challenges.`,
      category: 'Non-Technical',
      date: 'Feb 21',
      time: '9:30 AM',
      rules: [
        'Event duration is 1.5 hours per slot',
        'Teams must solve clues sequentially',
        'Mobile phones are allowed for QR scanning',
        'Do not tamper with clues',
        'Fastest team to finish wins',
      ],
      fees: 50,
      wplink: 'https://chat.whatsapp.com/KF72JiRa80cLoul2V1LoUv',
      contact: {
        name1: 'Jhanavi',
        phone1: '9384654366',
        name2: 'Nivetha',
        phone2: '9840077658',
      },
      fallbackImage: './assets/fall_back/treasure_hunt.webp',
    },
    {
      title: 'Ninja Coding',
      id: '4',
      image:
        'https://firebasestorage.googleapis.com/v0/b/tekhora-26.firebasestorage.app/o/Ninja%20Coding.webp?alt=media&token=0190689a-283e-4b59-91e9-02756bea1a14',
      backside: './assets/Dustin.webp',
      description: `A competitive coding event testing aptitude, problem-solving skills, and programming ability.`,
      teamSize: '2-3',
      category: 'Technical',
      date: 'Feb 21',
      time: '9:30 AM',
      rules: [
        'On-spot registration is available',
        'Up to 2 members per team',
        'Prelims contain objective questions',
        'Finals consist of competitive coding challenges',
      ],

      fees: 60,
      wplink: 'https://chat.whatsapp.com/K4iN3HWHWmn9kEoTmfBH9U',
      contact: {
        name1: 'Mekesh',
        phone1: '9952598472',
        name2: 'Rasheen Fahmi',
        phone2: '7867896416',
      },
      fallbackImage: './assets/fall_back/ninja_coding.webp',
    },
    {
      title: 'ADZAP',
      id: '5',
      image:
        'https://firebasestorage.googleapis.com/v0/b/tekhora-26.firebasestorage.app/o/adzap.webp?alt=media&token=6bb6ec19-4fa6-4103-bf62-aa7bd89a08a0',
      backside: './assets/Max.webp',
      description: `Teams create creative and humorous advertisements for imaginary or bizarre products within a limited time.`,
      category: 'Non-Technical',
      teamSize: '2-3',
      date: 'Feb 21',
      time: '9:30 AM',
      rules: [
        'Teams must have 2 to 3 participants',
        'Topics are given on the spot',
        'Judging based on creativity, humor, and presentation',
        'No offensive content allowed',
        'Time limit violations lead to penalties',
        'Judges’ decisions are final',
      ],
      fees: 50,
      wplink: 'https://chat.whatsapp.com/KNHsMcfMAkG7bgSy8trA4W',
      contact: {
        name1: 'Sudhahar',
        phone1: '9363595133',
        name2: 'Karthik Raja',
        phone2: '9361139648',
      },
      fallbackImage: './assets/fall_back/adzap.webp',
    },
    {
      title: 'coding with AI',
      id: '2',
      image:
        'https://firebasestorage.googleapis.com/v0/b/tekhora-26.firebasestorage.app/o/Coding%20with%20AI.webp?alt=media&token=41ec379d-9d3f-4c1f-9824-7a689ff8423f',
      backside: './assets/vecna.webp',
      description: `Coding with AI is a two-round competition that tests AI knowledge, coding skills, and machine learning abilities. Participants solve logic questions and build ML models using datasets. Winners are decided based on ML performance.`,
      category: 'Technical',
      teamSize: '2-3',
      date: 'Feb 21',
      time: '9:30 AM',
      rules: [
        'Maximum 2 members per team',
        'Only qualified teams move to Round 2',
        'AI tools may be used for guidance and code generation',
        'Final winners decided purely on Round 2 performance',
      ],
      fees: 60,
      wplink:
        'https://chat.whatsapp.com/GLmmzP7Vz8nKgTtq55QBS0https://chat.whatsapp.com/GLmmzP7Vz8nKgTtq55QBS0',
      contact: {
        name1: 'SriLakshmi',
        phone1: '9566208249',
        name2: 'Rakshitha',
        phone2: '8610209696',
      },
      fallbackImage: './assets/fall_back/coding_with_ai.webp',
    },
    {
      title: 'Fandom Quiz',
      id: '7',
      image:
        'https://firebasestorage.googleapis.com/v0/b/tekhora-26.firebasestorage.app/o/fandom_quiz.webp?alt=media&token=407abbd8-f32b-43ce-8533-374a937cf20c',
      backside: './assets/Nancy.webp',
      teamSize: '2-3',
      description: `A quiz event covering movies, anime, TV shows, and pop culture to test true fandom knowledge.`,
      category: 'Non-Technical',
      date: 'Feb 21',
      time: '9:30 AM',
      rules: [
        'Only registered teams may participate',
        'Prelims will be disclosed on the spot',
        'Finals include three quiz segments',
        'Points and buzzers handled by quizmasters',
        'Quizmaster’s decision is final',
      ],
      fees: 50,
      wplink: 'https://chat.whatsapp.com/IP1xXPn9cPZAG4VvxzzVpi',
      contact: {
        name1: 'Pragadheeshwaran',
        phone1: '8903098801',
        name2: 'Ganesh',
        phone2: '7339532544',
      },
      fallbackImage: './assets/fall_back/fandom_quiz.webp',
    },
  ];

  return <eventcontext.Provider value={eventext}>{children}</eventcontext.Provider>;
}

export default Eventprovider;
