import { Signeventscontext } from './SEvents.context';

const SignEventProvider = ({ children }) => {
  const workshops = [
    {
      title: 'Hackathon',
      id: '16',
      image:
        'https://firebasestorage.googleapis.com/v0/b/tekhora-26.firebasestorage.app/o/hackathon.webp?alt=media&token=4040803f-61c6-4a45-b5e1-76779ffe3052',
      backside: './assets/Billy.webp',
      description:
        ' Our Hackathon is an exciting innovation challenge that brings together creative minds to solve real-world problems using technology. Participants collaborate, build prototypes and present impactful solutions within a limited time\n\n🥇 Winner Team:\n₹5000 Cash Prize + ₹4000 worth 1-Month Internship Voucher\n🥈 Runner-Up Team:\n₹3000 Cash Prize + ₹2000 worth 2-Weeks Internship Voucher\n🎖️ Additional Benefits:\nParticipation Certificates Mentorship Opportunities Recognition',
      category: 'Technical',
      isSignature: true,
      miniTeamSize: '2',
      teamSize: '4',
      date: '2026-02-22',
      time: '9.30am to 5pm',
      rules: ['Rules'],
      fees: 499,
      wplink: 'https://chat.whatsapp.com/DIz6Lqd00DIE75JTfN5EKq',
      contact: {
        name1: 'Sandheep',
        phone1: '9884793806',
        name2: 'Rahul',
        phone2: '9159812736',
      },
      //fallbackImage: './assets/fall_back/hackathon.webp',
    },
    {
      title: 'MUN Debate',
      id: '17',
      image:
        'https://firebasestorage.googleapis.com/v0/b/tekhora-26.firebasestorage.app/o/MUN.webp?alt=media&token=7dc12f48-9d39-45a3-9399-4265d884a87e',
      backside: './assets/Billy.webp',
      description:
        'We are proud to present a one-day, high-impact MUN organized with Youthalic, a leader in shaping confident communicators. More than a simulation, this immersive experience empowers young minds to step into the shoes of global leaders to debate real-world issues and craft meaningful solutions.',
      category: 'Technical',
      isSignature: true,
      teamSize: '1',
      date: '2026-02-22',
      time: '9.30am to 5pm',
      rules: [
        'English is the official and working language for all formal and informal debate.',
        'Delegates must maintain diplomacy, respect, and decorum at all times.',
        'EB instructions must be followed without delay; violations may lead to warnings or removal.',
        'Rules apply to all Youthalic committees, including UN-style and Indian-style variations.',
        'The EB has complete control over proceedings, recognizing speakers, and ruling on motions.',
        'The EB may make oral or written statements to the committee at any time.',
        'The standard flow includes Roll Call, Agenda setting, GSL, Debate, and Voting.',
        'Attendance requires responding with "Present" or "Present and Voting".',
        'The agenda is set by motion followed by a simple majority vote.',
        'The GSL is the main queue where each speech must take at least two Points of Information (POIs).',
        'POI time is separate from the main speaking time.',
        'Delegates may yield remaining time to another delegate, POIs, or the Chair.',
        'Yields cannot be re-yielded to a third party.',
        'A Point of Order may be raised immediately after a speech to correct a factual inaccuracy.',
        'A Point of Personal Privilege is raised for comfort or audibility and may interrupt a speaker.',
        'A Point of Parliamentary Inquiry is used to ask the EB about rules or procedure.',
        'A Right of Reply is granted in writing if a delegate feels personally or nationally offended.',
        'A Moderated Caucus focuses on subtopics with specified total time and speaker time.',
        'An Unmoderated caucus allows for informal discussion and drafting for a specified duration.',
        'Crossfire is a 3-minute face-to-face debate between two volunteers moderated by the EB.',
        'Any delegate may motion for a 30-second Moment of Inspiration for committee unity.',
        'The EB may pose a Chair’s Challenge surprise scenario to break a debate deadlock.',
        'Blended Debate Mode mixes GSL speeches with short Q&A for 5 minutes.',
        'Procedural motions require a simple majority; draft resolutions require a 2/3 majority.',
        'Once voting begins, the room is locked, and silence is required.',
        'A Roll Call Vote is a recorded name-by-name vote of Yes, No, or Abstain.',
        'Open Talk is a free-form circle discussion ending in a symbolic declaration.',
        'A Press Conference involves the International Press questioning delegates.',
        'The POI Streak Award is given to the most active quality questioner.',
        'Suspension of rules requires a simple majority and EB approval.',
      ],
      fees: 299,
      wplink: 'https://chat.whatsapp.com/BOMIVFVlFfmKXlf5SakQvk',
      contact: {
        name1: 'Rithikesh J',
        phone1: '8667688159',
      },
      //fallbackImage: './assets/fall_back/hackathon.webp',
    },
    {
      title: 'Paper Presentation',
      id: '18',
      image:
        'https://firebasestorage.googleapis.com/v0/b/tekhora-26.firebasestorage.app/o/Paper%20Presentation.webp?alt=media&token=c34772fa-11f2-4135-9677-be1888ad2d3d',
      backside: './assets/Robin.webp',
      description:
        'The Paper Presentation is an academic event that provides a platform for participants to present their research ideas, innovations, and findings on emerging topics. It encourages knowledge sharing, critical thinking, and communication skills.',
      category: 'Technical',
      isSignature: true,
      date: '2026-02-21',
      time: '9.30am-5pm',
      rules: ['Rules'],
      miniTeamSize: '1',
      teamSize: '2',
      fees: 199,
      wplink: 'https://chat.whatsapp.com/B5qGEmOOVF8JkBub5bvwg1',
      contact: {
        name1: 'Poorna Prakash',
        phone1: '8838730894',
        name2: 'Nitin Pranav',
        phone2: '9123591494',
      },
      //fallbackImage: './assets/fall_back/paper_presentation.webp',
    },
  ];
  return <Signeventscontext.Provider value={workshops}>{children}</Signeventscontext.Provider>;
};
export default SignEventProvider;
