// eslint-disable-next-line no-unused-vars
import { workshopcontext } from './workshop.context';

function WorkshoProvider({ children }) {
  const OtherEvents = [
    {
      title: 'Workshop1',
      id: '10',
      image: '/workshop1.png',
      backside: './assets/Henry.webp',
      description: 'This is workshop 1',
      category: 'Technical',
      isSignature: true,
      date: '2026-02-21',
      time: '11:00 AM',
      rules: ['Rules'],
      fees: 499,
      contact: {
        name1: 'Dipakumar',
        phone1: '7639933600',
        name2: 'Ramkumar',
        phone2: '8825538554',
      },
      fallbackImage: './assets/fall_back/workshop.webp',
    },
    {
      title: 'Workshop2',
      id: '11',
      image: '/workshop2.png',
      backside: './assets/jonathan.webp',
      description: 'This is workshop 2',
      category: 'Technical',
      isSignature: true,
      date: '2026-02-21',
      time: '11:00 AM',
      rules: ['Rules'],
      fees: 499,
      contact: {
        name1: 'Kamalnath',
        phone1: '9150580147',
        name2: 'Albin Joseph',
        phone2: '9566322365',
      },
      fallbackImage: './assets/fall_back/workshop.webp',
    },
    {
      title: 'Workshop3',
      id: '12',
      image: '/workshop1.png',
      backside: './assets/Henry.webp',
      description: 'This is workshop 1',
      category: 'Technical',
      isSignature: true,
      date: '2026-02-21',
      time: '11:00 AM',
      rules: ['Rules'],
      fees: 499,
      contact: {
        name1: 'Dipakumar',
        phone1: '7639933600',
        name2: 'Ramkumar',
        phone2: '8825538554',
      },
      fallbackImage: './assets/fall_back/workshop.webp',
    },
    {
      title: 'Workshop4',
      id: '13',
      image: '/workshop1.png',
      backside: './assets/Henry.webp',
      description: 'This is workshop 1',
      category: 'Technical',
      isSignature: true,
      date: '2026-02-21',
      time: '11:00 AM',
      rules: ['Rules'],
      fees: 499,
      contact: {
        name1: 'Dipakumar',
        phone1: '7639933600',
        name2: 'Ramkumar',
        phone2: '8825538554',
      },
      fallbackImage: './assets/fall_back/workshop.webp',
    },
    {
      title: 'Workshop5',
      id: '14',
      image: '/workshop1.png',
      backside: './assets/Henry.webp',
      description: 'This is workshop 1',
      category: 'Technical',
      isSignature: true,
      date: '2026-02-21',
      time: '11:00 AM',
      rules: ['Rules'],
      fees: 499,
      contact: {
        name1: 'Dipakumar',
        phone1: '7639933600',
        name2: 'Ramkumar',
        phone2: '8825538554',
      },
      fallbackImage: './assets/fall_back/workshop.webp',
    },
    {
      title: 'Workshop6',
      id: '15',
      image: '/workshop1.png',
      backside: './assets/Henry.webp',
      description: 'This is workshop 1',
      category: 'Technical',
      isSignature: true,
      date: '2026-02-21',
      time: '11:00 AM',
      rules: ['Rules'],
      fees: 499,
      contact: {
        name1: 'Dipakumar',
        phone1: '7639933600',
        name2: 'Ramkumar',
        phone2: '8825538554',
      },
      fallbackImage: './assets/fall_back/workshop.webp',
    },
  ];
  return <workshopcontext.Provider value={OtherEvents}>{children}</workshopcontext.Provider>;
}

export default WorkshoProvider;
