// eslint-disable-next-line no-unused-vars
import { workshopcontext } from './workshop.context';

function WorkshoProvider({ children }) {
  const OtherEvents = [
    {
      title: 'Big Data & Analytics',
      alt: 'AIA SYMPO TEKHORA26 BIG DATA AND ANALYTICS WORKSHOP',
      id: '10',
      image:
        'https://firebasestorage.googleapis.com/v0/b/tekhora-26.firebasestorage.app/o/WORKSHOP%201.webp?alt=media&token=594186d8-0d1b-41a2-8d5c-3cd2126faa0d',
      backside: './assets/Henry.webp',
      description: 'This is Big Data & Analytics Workshop',
      category: 'Technical',
      isSignature: false,
      date: '2026-02-21',
      time: '11:00 AM',
      rules: ['Rules'],
      fees: 599,
      wplink: 'https://chat.whatsapp.com/Lm6YJ4VWSbWANQ2r7OYz4F ',
      contact: {
        name1: 'Dipakumar',
        phone1: '7639933600',
        name2: 'Ramkumar',
        phone2: '8825538554',
      },
      fallbackImage: './assets/fall_back/workshop.webp',
    },
    {
      title: 'Spring Fusion',
      alt: 'AIA SYMPO TEKHORA26 SPRING FUSION WORKSHOP',
      id: '11',
      image:
        'https://firebasestorage.googleapis.com/v0/b/tekhora-26.firebasestorage.app/o/WORKSHOP%202.webp?alt=media&token=77cb4aec-92d2-44c3-bfaa-65264cdc1eb5',
      backside: './assets/jonathan.webp',
      description: 'This is Spring Fusion Workshop',
      category: 'Technical',
      isSignature: false,
      date: '2026-02-21',
      time: '11:00 AM',
      rules: ['Rules'],
      fees: 399,
      wplink: 'https://chat.whatsapp.com/GroOu44XweE1UeClMHLR8v ',
      contact: {
        name1: 'Kamalnath',
        phone1: '9150580147',
        name2: 'Albin Joseph',
        phone2: '9566322365',
      },
      fallbackImage: './assets/fall_back/workshop.webp',
    },
    {
      title: 'LLM Stack',
      alt: 'AIA SYMPO TEKHORA26 LLM STACK WORKSHOP',
      id: '12',
      image:
        'https://firebasestorage.googleapis.com/v0/b/tekhora-26.firebasestorage.app/o/WORKSHOP%203.webp?alt=media&token=8d2a9739-e7b9-479a-9199-ab9d4586082c',
      backside: './assets/Henry.webp',
      description: 'This is LLM Stack Workshop',
      category: 'Technical',
      isSignature: false,
      date: '2026-02-21',
      time: '11:00 AM',
      rules: ['Rules'],
      fees: 599,
      wplink: 'https://chat.whatsapp.com/KYPB9QSyS6H9gw7Mk802Fo',
      contact: {
        name1: 'Dipakumar',
        phone1: '7639933600',
        name2: 'Ramkumar',
        phone2: '8825538554',
      },
      fallbackImage: './assets/fall_back/workshop.webp',
    },
    {
      title: 'Physical AI',
      alt: 'AIA SYMPO TEKHORA26 PHYSICAL AI WORKSHOP',
      id: '13',
      image:
        'https://firebasestorage.googleapis.com/v0/b/tekhora-26.firebasestorage.app/o/WORKSHOP%204.webp?alt=media&token=7ab40ab9-40ff-4e7d-9b16-884eab14fc78',
      backside: './assets/Henry.webp',
      description: 'This is Physical AI Workshop',
      category: 'Technical',
      isSignature: false,
      date: '2026-02-21',
      time: '11:00 AM',
      rules: ['Rules'],
      fees: 599,
      wplink: 'https://chat.whatsapp.com/JrHZ94hO3EsIabJQg8CVGx ',
      contact: {
        name1: 'Dipakumar',
        phone1: '7639933600',
        name2: 'Ramkumar',
        phone2: '8825538554',
      },
      fallbackImage: './assets/fall_back/workshop.webp',
    },
    {
      title: 'LLMS 101',
      alt: 'AIA SYMPO TEKHORA26 LLMS 101 WORKSHOP',
      id: '14',
      image:
        'https://firebasestorage.googleapis.com/v0/b/tekhora-26.firebasestorage.app/o/WORKSHOP%205.webp?alt=media&token=c90589ef-9280-4dc3-974d-bc3fde8f1c4e',
      backside: './assets/Henry.webp',
      description: 'This is LLMS 101 Workshop',
      category: 'Technical',
      isSignature: false,
      date: '2026-02-21',
      time: '11:00 AM',
      rules: ['Rules'],
      fees: 599,
      wplink: 'https://chat.whatsapp.com/Hne1yl9WgCs3FY8XUddKHC',
      contact: {
        name1: 'Dipakumar',
        phone1: '7639933600',
        name2: 'Ramkumar',
        phone2: '8825538554',
      },
      fallbackImage: './assets/fall_back/workshop.webp',
    },
    {
      title: 'Data Science',
      alt: 'AIA SYMPO TEKHORA26 DATA SCIENCE WORKSHOP',
      id: '15',
      image:
        'https://firebasestorage.googleapis.com/v0/b/tekhora-26.firebasestorage.app/o/WORKSHOP%206.webp?alt=media&token=97f0bfd9-5568-4fc5-8e81-cd0e2261fc13',
      backside: './assets/Henry.webp',
      description: 'This is Data Science Workshop',
      category: 'Technical',
      isSignature: false,
      date: '2026-02-21',
      time: '11:00 AM',
      rules: ['Rules'],
      fees: 350,
      wplink: 'https://chat.whatsapp.com/JxwEKj1dIL6LVzVi5UaZoI',
      contact: {
        name1: 'Dipakumar',
        phone1: '7639933600',
        name2: 'Ramkumar',
        phone2: '8825538554',
      },
      fallbackImage: './assets/fall_back/workshop.webp',
    },
  ];
  return <workshopcontext.Provider value={OtherEvents}>{children}</workshopcontext.Provider>;
}

export default WorkshoProvider;
