// eslint-disable-next-line no-unused-vars
import { workshopcontext } from './workshop.context';

function WorkshoProvider({ children }) {
  const OtherEvents = [
    {
      title: 'Modern Big Data Analytics',
      alt: 'AIA SYMPO TEKHORA26 BIG DATA AND ANALYTICS WORKSHOP',
      id: '10',
      image:
        'https://firebasestorage.googleapis.com/v0/b/tekhora-26.firebasestorage.app/o/WORKSHOP%201.webp?alt=media&token=594186d8-0d1b-41a2-8d5c-3cd2126faa0d',
      backside: './assets/Henry.webp',
      company: 'BNY',
      trainer: 'Mehal',
      description: [
        'Introduction to Big Data & Industry Use Cases',
        'Big Data Engineering vs Big Data Analytics - Roles & Skills',
        'Big Data Architecture & Ecosystem Overview',
        'Apache Spark Fundamentals',
        'Databricks Platform Overview & Workspace Demo',
        'Data Ingestion & ETL Pipelines in Big Data Engineering',
        'Distributed Data Processing using Spark (Hands-on)',
        'Big Data Analytics using Spark SQL & DataFrames',
        'Building AI Applications on Big Data',
        'Career Pathways & Industry Trends in Big Data Engineering',
      ],
      category: 'workshop',
      isSignature: false,
      date: '2026-02-22',
      time: '9:00 AM - 5:00 PM',
      rules: ['Rules'],
      fees: 599,
      wplink: 'https://chat.whatsapp.com/Lm6YJ4VWSbWANQ2r7OYz4F ',
      contact: {
        name1: 'Jaiprakash S ',
        phone1: '6369472631',
        name2: 'Yuvarani S',
        phone2: '9344094383',
      },
      fallbackImage: './assets/fall_back/workshop.webp',
    },
    {
      title: 'Spring Fusion',
      alt: 'AIA SYMPO TEKHORA26 SPRING FUSION WORKSHOP',
      id: '11',
      image:
        'https://firebasestorage.googleapis.com/v0/b/tekhora-26.firebasestorage.app/o/WORKSHOP%202.webp?alt=media&token=77cb4aec-92d2-44c3-bfaa-65264cdc1eb5',
      backside: './assets/jonathan.webp',
      company: 'BNY',
      trainer: 'Gayathri',
      description: [
        'Spring Boot Basics',
        'REST API Development',
        'Layered Backend Design',
        'Database Integration',
        'Validation & Exception Handling',
        'Configuration & Best Practices',
        'Introduction to Spring AI',
        'Live Demos: AI-powered backend endpoint',
      ],
      category: 'workshop',
      isSignature: false,
      date: '2026-02-21',
      time: '1:00 PM - 5:00 PM',
      rules: ['Rules'],
      fees: 399,
      wplink: 'https://chat.whatsapp.com/GroOu44XweE1UeClMHLR8v ',
      contact: {
        name1: 'Dipakumar',
        phone1: '7639933600',
        name2: 'Ramkumar',
        phone2: ' 8825538554',
      },
      fallbackImage: './assets/fall_back/workshop.webp',
    },
    {
      title: 'LLM Stack',
      alt: 'AIA SYMPO TEKHORA26 LLM STACK WORKSHOP',
      id: '12',
      image:
        'https://firebasestorage.googleapis.com/v0/b/tekhora-26.firebasestorage.app/o/WORKSHOP%203.webp?alt=media&token=8d2a9739-e7b9-479a-9199-ab9d4586082c',
      backside: './assets/branner.webp',
      company: 'Zenardy Technologies',
      trainer: 'Akash',
      description: [
        'Introduction to LLM System Design',
        'Local Fine-Tuning of Open-Source LLMs',
        'Prompt Engineering & Evaluation Basics',
        'Observability with Langfuse',
        'Experiment Tracking & Model Evaluation',
        'Containerizing AI Applications with Docker',
        'MCP for Modular AI Orchestration',
      ],
      category: 'workshop',
      isSignature: false,
      date: '2026-02-22',
      time: '9:00 AM - 5:00 PM',
      rules: ['Rules'],
      fees: 599,
      wplink: 'https://chat.whatsapp.com/Fl2bctBwY785JCxCkqxZaQ',
      contact: {
        name1: 'Pragadeeshwaran',
        phone1: '8903098801',
        name2: 'Ganesh',
        phone2: ' 7339532544',
      },
      fallbackImage: './assets/fall_back/workshop.webp',
    },
    {
      title: 'Physical AI',
      alt: 'AIA SYMPO TEKHORA26 PHYSICAL AI WORKSHOP',
      id: '13',
      image:
        'https://firebasestorage.googleapis.com/v0/b/tekhora-26.firebasestorage.app/o/WORKSHOP%204.webp?alt=media&token=7ab40ab9-40ff-4e7d-9b16-884eab14fc78',
      backside: './assets/eddie.webp',
      company: 'Tekion',
      trainer: 'TBD',
      description: [
        'Introduction to Physical AI',
        'Core loop (Sense → Think/Plan → Act)',
        'Hardware basics - sensors, actuators, compute',
        'ROS - Robotic Operating System',
        'Perception & SLAM',
        'Planning, Navigation & Control',
        'Learning for Physical AI (VLA Models)',
        'Safety, Testing, and Deployment',
      ],
      category: 'workshop',
      isSignature: false,
      date: '2026-02-21',
      time: '9:00 AM - 5:00 PM',
      rules: ['Rules'],
      fees: 599,
      wplink: 'https://chat.whatsapp.com/JrHZ94hO3EslabJQg8CVGx',
      contact: {
        name1: 'Kamalnath',
        phone1: '9150580147',
        name2: 'Albin Joseph',
        phone2: '9566322365',
      },
      fallbackImage: './assets/fall_back/workshop.webp',
    },
    {
      title: 'LLMS 101',
      alt: 'AIA SYMPO TEKHORA26 LLMS 101 WORKSHOP',
      id: '14',
      image:'https://firebasestorage.googleapis.com/v0/b/tekhora-26.firebasestorage.app/o/Posters%2FWorkShop%2FWORKSHOP%205.webp?alt=media&token=9477daea-e4d7-4f63-95cc-7b42a9cf23df',
      backside: './assets/wheelers.webp',
      trainer: 'Bhuvaneshwari,K.Harshitha',
      description: [
        'Evolution of Language AI',
        'Transformer Architecture',
        'Encoder-only vs Decoder-only Models',
        'Tokenization & Embeddings',
        'Training Methodologies',
        'Text Generation & Ethics',
        'Hands-on Demo',
      ],
      category: 'workshop',
      isSignature: false,
      date: '2026-02-22',
      time: '9:00 AM - 5:00 PM',
      rules: ['Rules'],
      fees: 599,
      wplink: 'https://chat.whatsapp.com/Hne1yl9WgCs3FY8XUddKHC',
      contact: {
        name1: 'Ithikash',
        phone1: '9786398639',
        name2: 'Joel',
        phone2: '6381165383',
      },
      fallbackImage: './assets/fall_back/workshop.webp',
    },
    {
      title: 'Data Science',
      alt: 'AIA SYMPO TEKHORA26 DATA SCIENCE WORKSHOP',
      id: '15',
      image:
        'https://firebasestorage.googleapis.com/v0/b/tekhora-26.firebasestorage.app/o/WORKSHOP%206.webp?alt=media&token=97f0bfd9-5568-4fc5-8e81-cd0e2261fc13',
      backside: './assets/erica.webp',
      company: 'CTS',
      trainer: 'Balachandar Ganesan',
      description: [
        'Data vs Insights Introduction',
        'ML Algorithms (Regression, Trees, SVM)',
        'Nature of Data & ML Methods Pros/Cons',
        'Development & Business Constraints',
        'Case Study: Insights from Data',
      ],
      category: 'workshop',
      isSignature: false,
      date: '2026-02-21',
      time: '9:00 AM - 1:00 PM',
      rules: ['Rules'],
      fees: 350,
      wplink: 'https://chat.whatsapp.com/JxwEKj1dIL6LVzVi5UaZol',
      contact: {
        name1: 'Dipakumar',
        phone1: '7639933600',
        name2: 'Ramkumar',
        phone2: '8825538554',
      },
      fallbackImage: './assets/fall_back/workshop.webp',
    },
  ];

  return <workshopcontext.Provider value={OtherEvents}>{children}</workshopcontext.Provider>;
}

export default WorkshoProvider;
